apiVersion: apps/v1
kind: Deployment
metadata:
  name: userX-health-nginx
  namespace: userX-namespace
  labels:
    app: health-nginx
    owner: userX
spec:
  replicas: 3
  selector:
    matchLabels:
      app: health-nginx
      owner: userX
  template:
    metadata:
      labels:
        app: health-nginx
        owner: userX
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20