apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userX-delayed-storage
  namespace: userX-namespace
  labels:
    app: delayed-storage-demo
    owner: userX
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 1Gi