apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userX-fast-storage
  namespace: userX-namespace
  labels:
    app: fast-storage-demo
    owner: userX
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 1Gi