apiVersion: v1
kind: Pod
metadata:
  name: userX-storage-writer
  namespace: userX-namespace
  labels:
    app: storage-writer
    owner: userX
spec:
  containers:
  - name: writer
    image: busybox:1.35
    command: ['sh', '-c', 'while true; do sleep 30; done']
    volumeMounts:
    - name: data-volume
      mountPath: /data
    resources:
      requests:
        memory: "32Mi"
        cpu: "25m"
      limits:
        memory: "64Mi"
        cpu: "50m"
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: userX-basic-storage