apiVersion: v1
kind: Pod
metadata:
  name: userX-configmap-nginx
  namespace: userX-namespace
  labels:
    app: nginx
    owner: userX
    type: configmap-demo
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    env:
    - name: APP_NAME
      valueFrom:
        configMapKeyRef:
          name: userX-config
          key: app.name
    - name: APP_VERSION
      valueFrom:
        configMapKeyRef:
          name: userX-config
          key: app.version
    - name: OWNER
      value: "userX"