apiVersion: v1
kind: Pod
metadata:
  name: userX-multi-container
  namespace: userX-namespace
  labels:
    app: multi-app
    owner: userX
spec:
  containers:
  - name: nginx-container
    image: nginx:1.21
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
  - name: busybox-container
    image: busybox:1.35
    command: ['sh', '-c', 'while true; do echo "$(date): Hello from busybox"; sleep 30; done']
    resources:
      requests:
        memory: "32Mi"
        cpu: "25m"
      limits:
        memory: "64Mi"
        cpu: "50m"