apiVersion: v1
kind: Pod
metadata:
  name: userX-problematic-nginx
  namespace: userX-namespace
  labels:
    app: nginx
    owner: userX
    status: problematic
spec:
  containers:
  - name: nginx
    image: nginx:nonexistent-tag
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"