apiVersion: v1
kind: Pod
metadata:
  name: userX-resource-nginx
  namespace: userX-namespace
  labels:
    app: nginx
    owner: userX
    type: resource-demo
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    env:
    - name: NGINX_HOST
      value: "localhost"
    - name: NGINX_PORT
      value: "80"