apiVersion: v1
kind: Namespace
metadata:
  name: userX-namespace
  labels:
    name: userX-namespace
    purpose: training
    owner: userX
spec: {}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: userX-quota
  namespace: userX-namespace
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "5"
    count/deployments.apps: "10"
    count/replicasets.apps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: userX-limits
  namespace: userX-namespace
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container