apiVersion: apps/v1
kind: Deployment
metadata:
  name: userX-limited-resources
  namespace: userX-namespace
  labels:
    app: limited-resources
spec:
  replicas: 1
  selector:
    matchLabels:
      app: limited-resources
  template:
    metadata:
      labels:
        app: limited-resources
    spec:
      containers:
      - name: limited-app
        image: node:18-alpine
        command: ["sh", "-c"]
        args:
        - |
          cat > server.js << 'EOF'
          const http = require('http');
          const crypto = require('crypto');

          const server = http.createServer((req, res) => {
            if (req.url === '/cpu-load') {
              console.log('CPU load request received (limited resources)');
              const start = Date.now();
              while (Date.now() - start < 3000) {
                crypto.createHash('sha256').update(Math.random().toString()).digest('hex');
              }
              res.writeHead(200, {'Content-Type': 'application/json'});
              res.end(JSON.stringify({
                message: 'CPU load generated (limited)',
                pod: process.env.HOSTNAME,
                timestamp: new Date().toISOString()
              }));
            } else if (req.url === '/health') {
              res.writeHead(200, {'Content-Type': 'application/json'});
              res.end(JSON.stringify({
                status: 'healthy',
                uptime: process.uptime(),
                memory: process.memoryUsage()
              }));
            } else {
              res.writeHead(200, {'Content-Type': 'text/html'});
              res.end(`
                <h1>userX Limited Resources Application</h1>
                <p>Pod: ${process.env.HOSTNAME}</p>
                <p>This app has very limited CPU/memory resources</p>
                <p>Uptime: ${process.uptime().toFixed(2)} seconds</p>
                <p>Memory Usage: ${JSON.stringify(process.memoryUsage(), null, 2)}</p>
                <hr>
                <ul>
                  <li><a href="/cpu-load">Generate CPU Load</a></li>
                  <li><a href="/health">Health Check</a></li>
                </ul>
              `);
            }
          });

          server.listen(3000, () => {
            console.log('Limited resources app running on port 3000');
          });
          EOF
          node server.js
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10