apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: userX-limited-hpa
  namespace: userX-namespace
  labels:
    app: limited-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userX-limited-resources
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 45
      policies:
      - type: Pods
        value: 2
        periodSeconds: 45
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60