apiVersion: v1
kind: Service
metadata:
  name: userX-limited-service
  namespace: userX-namespace
  labels:
    app: limited-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: limited-resources