apiVersion: v1
kind: Pod
metadata:
  name: userX-load-generator
  namespace: userX-namespace
  labels:
    app: load-generator
spec:
  containers:
  - name: load-generator
    image: alpine:3.18
    command: ["sh", "-c"]
    args:
    - |
      apk add --no-cache curl
      echo "Load generator ready for userX"
      echo "Available services:"
      echo "- userX-cpu-app-service"
      echo "- userX-memory-app-service"
      echo "- userX-multi-metric-service"
      echo "- userX-limited-service"
      sleep 3600
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
  restartPolicy: Never