apiVersion: apps/v1
kind: Deployment
metadata:
  name: userX-multi-metric-app
  namespace: userX-namespace
  labels:
    app: multi-metric-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-metric-app
  template:
    metadata:
      labels:
        app: multi-metric-app
    spec:
      containers:
      - name: multi-metric-app
        image: node:18-alpine
        command: ["sh", "-c"]
        args:
        - |
          cat > server.js << 'EOF'
          const http = require('http');
          const crypto = require('crypto');
          let memoryStore = [];

          function cpuIntensiveTask(duration = 1000) {
            const start = Date.now();
            while (Date.now() - start < duration) {
              crypto.createHash('sha256').update(Math.random().toString()).digest('hex');
            }
          }

          function memoryIntensiveTask() {
            for (let i = 0; i < 500; i++) {
              memoryStore.push(new Array(5000).fill(Math.random()));
            }
            setTimeout(() => {
              memoryStore = memoryStore.slice(0, memoryStore.length / 2);
            }, 8000);
          }

          const server = http.createServer((req, res) => {
            if (req.url === '/cpu-load') {
              console.log('CPU load request received');
              cpuIntensiveTask(1500);
              res.writeHead(200, {'Content-Type': 'application/json'});
              res.end(JSON.stringify({
                message: 'CPU load generated',
                pod: process.env.HOSTNAME,
                timestamp: new Date().toISOString()
              }));
            } else if (req.url === '/memory-load') {
              console.log('Memory load request received');
              memoryIntensiveTask();
              res.writeHead(200, {'Content-Type': 'application/json'});
              res.end(JSON.stringify({
                message: 'Memory load generated',
                pod: process.env.HOSTNAME,
                memoryUsage: process.memoryUsage(),
                timestamp: new Date().toISOString()
              }));
            } else if (req.url === '/mixed-load') {
              console.log('Mixed load request received');
              cpuIntensiveTask(1000);
              memoryIntensiveTask();
              res.writeHead(200, {'Content-Type': 'application/json'});
              res.end(JSON.stringify({
                message: 'Mixed CPU and memory load generated',
                pod: process.env.HOSTNAME,
                memoryUsage: process.memoryUsage(),
                timestamp: new Date().toISOString()
              }));
            } else if (req.url === '/health') {
              res.writeHead(200, {'Content-Type': 'application/json'});
              res.end(JSON.stringify({
                status: 'healthy',
                uptime: process.uptime(),
                memory: process.memoryUsage()
              }));
            } else {
              res.writeHead(200, {'Content-Type': 'text/html'});
              res.end(`
                <h1>userX Multi-Metric Application</h1>
                <p>Pod: ${process.env.HOSTNAME}</p>
                <p>Uptime: ${process.uptime().toFixed(2)} seconds</p>
                <p>Memory Usage: ${JSON.stringify(process.memoryUsage(), null, 2)}</p>
                <hr>
                <h3>Load Generation Endpoints:</h3>
                <ul>
                  <li><a href="/cpu-load">Generate CPU Load</a></li>
                  <li><a href="/memory-load">Generate Memory Load</a></li>
                  <li><a href="/mixed-load">Generate Mixed Load</a></li>
                  <li><a href="/health">Health Check</a></li>
                </ul>
              `);
            }
          });

          server.listen(3000, () => {
            console.log('Multi-metric app running on port 3000');
          });
          EOF
          node --expose-gc server.js
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10