apiVersion: apps/v1
kind: Deployment
metadata:
  name: userX-tcp-probe-app
  labels:
    app: tcp-probe
    owner: userX
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-probe
  template:
    metadata:
      labels:
        app: tcp-probe
        owner: userX
    spec:
      containers:
      - name: app
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"