apiVersion: apps/v1
kind: Deployment
metadata:
  name: userX-anti-affinity
  namespace: userX-namespace
  labels:
    app: anti-affinity
    owner: userX
spec:
  replicas: 3
  selector:
    matchLabels:
      app: anti-affinity
      owner: userX
  template:
    metadata:
      labels:
        app: anti-affinity
        owner: userX
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - anti-affinity
                - key: owner
                  operator: In
                  values:
                  - userX
              topologyKey: kubernetes.io/hostname
      containers:
      - name: app
        image: nginx:1.21
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"