apiVersion: apps/v1
kind: Deployment
metadata:
  name: userX-backend-nodeselected
  namespace: userX-namespace
  labels:
    app: backend-nodeselected
    owner: userX
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-nodeselected
      owner: userX
  template:
    metadata:
      labels:
        app: backend-nodeselected
        owner: userX
    spec:
      nodeSelector:
        node-type: training
      containers:
      - name: backend
        image: nginx:1.21
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"