apiVersion: apps/v1
kind: Deployment
metadata:
  name: userX-preferred-affinity
  namespace: userX-namespace
  labels:
    app: preferred-affinity
    owner: userX
spec:
  replicas: 3
  selector:
    matchLabels:
      app: preferred-affinity
      owner: userX
  template:
    metadata:
      labels:
        app: preferred-affinity
        owner: userX
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 80
            preference:
              matchExpressions:
              - key: node-type
                operator: In
                values:
                - training
          - weight: 20
            preference:
              matchExpressions:
              - key: environment
                operator: In
                values:
                - education
      containers:
      - name: app
        image: nginx:1.21
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"