apiVersion: apps/v1
kind: Deployment
metadata:
  name: userX-redis
  namespace: userX-namespace
  labels:
    app: redis
    owner: userX
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      owner: userX
  template:
    metadata:
      labels:
        app: redis
        owner: userX
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        command: ["redis-server"]
        args: ["--save", "60", "1", "--loglevel", "warning"]