apiVersion: apps/v1
kind: Deployment
metadata:
  name: userX-web-app
  namespace: userX-namespace
  labels:
    app: web-app
    owner: userX
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
        owner: userX
    spec:
      containers:
      - name: web-app
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
        env:
        # Environment variables from ConfigMap
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: userX-app-config
              key: database_url
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: userX-app-config
              key: log_level
        - name: MAX_CONNECTIONS
          valueFrom:
            configMapKeyRef:
              name: userX-app-config
              key: max_connections
        - name: DEBUG_MODE
          valueFrom:
            configMapKeyRef:
              name: userX-app-config
              key: debug_mode
        # Environment variables from Secret
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: userX-db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: userX-db-secret
              key: password
        volumeMounts:
        # Mount ConfigMap as file
        - name: app-config-volume
          mountPath: /etc/config
          readOnly: true
        # Mount Secret as files
        - name: api-keys-volume
          mountPath: /etc/secrets
          readOnly: true
        - name: tls-volume
          mountPath: /etc/ssl/certs/app
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      # ConfigMap volume
      - name: app-config-volume
        configMap:
          name: userX-app-props
      # Secret volumes
      - name: api-keys-volume
        secret:
          secretName: userX-api-keys
      - name: tls-volume
        secret:
          secretName: userX-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: userX-web-app-service
  namespace: userX-namespace
  labels:
    app: web-app
    owner: userX
spec:
  selector:
    app: web-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP