apiVersion: apps/v1
kind: Deployment
metadata:
  name: userX-canary-stable
  namespace: userX-namespace
  labels:
    app: canary-demo
    version: stable
    owner: userX
spec:
  replicas: 8  # 80% of traffic (stable version)
  selector:
    matchLabels:
      app: canary-demo
      version: stable
      owner: userX
  template:
    metadata:
      labels:
        app: canary-demo
        version: stable
        owner: userX
    spec:
      containers:
      - name: app
        image: nginx:1.21
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: "stable-v1.0"
        - name: DEPLOYMENT_TYPE
          value: "stable"
        - name: CANARY_WEIGHT
          value: "80"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5