apiVersion: apps/v1
kind: Deployment
metadata:
  name: userX-canary-version
  namespace: userX-namespace
  labels:
    app: canary-demo
    version: canary
    owner: userX
spec:
  replicas: 2  # 20% of traffic (canary version)
  selector:
    matchLabels:
      app: canary-demo
      version: canary
      owner: userX
  template:
    metadata:
      labels:
        app: canary-demo
        version: canary
        owner: userX
    spec:
      containers:
      - name: app
        image: nginx:1.22  # Newer version for canary
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: "canary-v2.0-beta"
        - name: DEPLOYMENT_TYPE
          value: "canary"
        - name: CANARY_WEIGHT
          value: "20"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5