apiVersion: apps/v1
kind: Deployment
metadata:
  name: userX-performance-app
  namespace: userX-namespace
  labels:
    app: performance-app
    owner: userX
spec:
  replicas: 5
  selector:
    matchLabels:
      app: performance-app
      owner: userX
  template:
    metadata:
      labels:
        app: performance-app
        owner: userX
    spec:
      containers:
      - name: performance-app
        image: nginx:1.21
        ports:
        - containerPort: 80
        env:
        - name: PERFORMANCE_TEST
          value: "enabled"
        - name: LOAD_GENERATION
          value: "high"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: userX-performance-service
  namespace: userX-namespace
  labels:
    app: performance-app
    owner: userX
spec:
  selector:
    app: performance-app
    owner: userX
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP