apiVersion: v1
kind: Pod
metadata:
  name: userX-different-nginx
  namespace: userX-namespace
  labels:
    app: different-nginx
    owner: userX
    purpose: demo
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"