apiVersion: v1
kind: Pod
metadata:
  name: userX-test-pod
  namespace: userX-namespace
  labels:
    app: test-pod
    owner: userX
spec:
  containers:
  - name: test-container
    image: nicolaka/netshoot:latest
    command: ['sh', '-c', 'while true; do sleep 30; done']
    resources:
      requests:
        memory: "32Mi"
        cpu: "25m"
      limits:
        memory: "64Mi"
        cpu: "50m"