apiVersion: apps/v1
kind: Deployment
metadata:
  name: userX-reader-app
  namespace: userX-namespace
  labels:
    app: reader-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader-app
  template:
    metadata:
      labels:
        app: reader-app
    spec:
      serviceAccountName: userX-app-reader
      containers:
      - name: reader-app
        image: alpine:3.18
        command: ["sh", "-c"]
        args:
        - |
          apk add --no-cache curl
          echo "Reader app with userX-app-reader service account"
          echo "This app can only read pods and logs"
          echo "Service account token location: /var/run/secrets/kubernetes.io/serviceaccount/token"
          echo "Namespace: $(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)"
          sleep 3600
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"