apiVersion: apps/v1
kind: Deployment
metadata:
  name: userX-minimal-app
  namespace: userX-namespace
  labels:
    app: minimal-app
    owner: userX
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minimal-app
      owner: userX
  template:
    metadata:
      labels:
        app: minimal-app
        owner: userX
    spec:
      serviceAccountName: userX-minimal-sa
      containers:
      - name: minimal-app
        image: busybox:1.35
        command: ['sleep', '3600']
        env:
        - name: PERMISSIONS
          value: "minimal"
        - name: USER_PREFIX
          value: "userX"
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: userX-minimal-service
  namespace: userX-namespace
  labels:
    app: minimal-app
    owner: userX
spec:
  selector:
    app: minimal-app
    owner: userX
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP