apiVersion: apps/v1
kind: Deployment
metadata:
  name: userX-admin-app
  namespace: userX-namespace
  labels:
    app: admin-app
    owner: userX
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-app
      owner: userX
  template:
    metadata:
      labels:
        app: admin-app
        owner: userX
    spec:
      serviceAccountName: userX-admin
      containers:
      - name: admin-app
        image: nginx:1.21
        ports:
        - containerPort: 80
        env:
        - name: ROLE
          value: "admin"
        - name: USER_PREFIX
          value: "userX"
        - name: ADMIN_PRIVILEGES
          value: "enabled"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: userX-admin-service
  namespace: userX-namespace
  labels:
    app: admin-app
    owner: userX
spec:
  selector:
    app: admin-app
    owner: userX
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP