apiVersion: batch/v1
kind: Job
metadata:
  name: userX-basic-job
  labels:
    app: basic-job
    owner: userX
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: worker
        image: busybox:1.35
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting basic job for userX..."
          echo "Processing data..."
          sleep 10
          echo "Job completed successfully!"
          echo "Results: Processed 100 items"
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "200m"