apiVersion: batch/v1
kind: CronJob
metadata:
  name: userX-basic-cronjob
  labels:
    app: scheduled-task
    owner: userX
spec:
  schedule: "*/2 * * * *"  # Every 2 minutes
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: scheduler
            image: busybox:1.35
            command:
            - /bin/sh
            - -c
            - |
              echo "Scheduled task running at $(date)"
              echo "User: userX"
              echo "Task ID: $(date +%s)"
              echo "Performing scheduled maintenance..."
              sleep 5
              echo "Scheduled task completed successfully!"
            resources:
              requests:
                memory: "32Mi"
                cpu: "100m"
              limits:
                memory: "64Mi"
                cpu: "200m"