apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: userX-namespace
  name: userX-configmap-manager
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: userX-namespace
  name: userX-deployment-manager
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: userX-configmap-manager-binding
  namespace: userX-namespace
subjects:
- kind: ServiceAccount
  name: userX-configmap-manager-sa
  namespace: userX-namespace
roleRef:
  kind: Role
  name: userX-configmap-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: userX-deployment-manager-binding
  namespace: userX-namespace
subjects:
- kind: ServiceAccount
  name: userX-deployment-manager-sa
  namespace: userX-namespace
roleRef:
  kind: Role
  name: userX-deployment-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: userX-configmap-manager-sa
  namespace: userX-namespace
  labels:
    purpose: configmap-management
    owner: userX
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: userX-deployment-manager-sa
  namespace: userX-namespace
  labels:
    purpose: deployment-management
    owner: userX