apiVersion: batch/v1
kind: Job
metadata:
  name: userX-parallel-job
  labels:
    app: parallel-job
    owner: userX
spec:
  parallelism: 3
  completions: 6
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: worker
        image: busybox:1.35
        command:
        - /bin/sh
        - -c
        - |
          echo "Worker pod $(hostname) starting..."
          WORKER_ID=$(echo $(hostname) | grep -o '[0-9]*$')
          echo "Processing batch $WORKER_ID..."
          sleep 15
          echo "Worker $WORKER_ID completed successfully!"
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "200m"