apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: userX-resource-app-hpa
  namespace: userX-namespace
  labels:
    app: resource-app
    owner: userX
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userX-resource-app
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70