apiVersion: v1
kind: ResourceQuota
metadata:
  name: userX-resource-quota
  namespace: userX-namespace
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "10"
    persistentvolumeclaims: "4"
    services: "5"
    count/deployments.apps: "5"
    count/replicasets.apps: "10"