apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: training-cluster
  region: us-east-2

nodeGroups:
- name: workers
  instanceType: m5.large
  desiredCapacity: 2
  minSize: 2
  maxSize: 2
  amiFamily: AmazonLinux2